# -*- coding: utf-8 -*-
"""project_2-2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C6LMy-YZaddcnRO8gxLSrSQM5zWq-4BO
"""

import pandas as pd

# 데이터셋 불러오기
data = pd.read_csv('2019_kbo_for_kaggle_v2.csv')

# 1) 2015~2018년까지 각 해의 상위 10명의 안타, 타율, 홈런, 출루율 출력
print("\n----각 해의 상위 10명 선수 출력하기 -----")
for year in range(2015, 2019):
    print(f"\n \t <{year}년> ")
    year_data = data[data['year'] == year]

    # 안타 상위 10명 출력
    hits_top10 = year_data.sort_values(by='H', ascending=False).head(10)
    print("\n\t 안타")
    print(hits_top10[['batter_name', 'H']])

    # 타율 상위 10명 출력
    avg_top10 = year_data.sort_values(by='avg', ascending=False).head(10)
    print("\n\t 타율")
    print(avg_top10[['batter_name', 'avg']])

    # 홈런 상위 10명 출력
    hr_top10 = year_data.sort_values(by='HR', ascending=False).head(10)
    print("\n\t 홈런")
    print(hr_top10[['batter_name', 'HR']])

    # 출루율 상위 10명 출력
    obp_top10 = year_data.sort_values(by='OBP', ascending=False).head(10)
    print("\n\t 출루율")
    print(obp_top10[['batter_name', 'OBP']])

# 2) 2018년에 각 포지션별로 승리 기여도가 가장 높은 선수 출력
year_2018 = data[data['year'] == 2018]
positions = ['포수', '1루수', '2루수', '3루수', '유격수', '좌익수', '중견수', '우익수']

print("\n----- 2018년 포지션별 승리 기여도 가장 높은 선수 -----")
for position in positions:
    position_data = year_2018[year_2018['cp'] == position]
    top_player = position_data[position_data['war'] == position_data['war'].max()]
    print(f"{position}: {top_player['batter_name'].iloc[0]}")

# 3) 연봉과 R, H, HR, RBI, SB, war, avg, OBP, SLG 간의 상관관계 계산 및 가장 높은 상관관계를 가진 항목 출력
correlation = data[['salary', 'R', 'H', 'HR', 'RBI', 'SB', 'war', 'avg', 'OBP', 'SLG']].corr()
salary_corr = correlation['salary']
highest_corr = salary_corr.abs().sort_values(ascending=False).index[1]
highest_corr_value = salary_corr[highest_corr]
print(f"\n----- 연봉과 가장 높은 상관관계를 가진 항목 -----")
print(f"상관계수: {highest_corr_value:.4f}")
print(f"{highest_corr}과의 상관관계가 가장 높음")